[package]
name = "chatServer_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
signal-hook = "0.3"


[[bin]]
name = "chatServer_rust"
path = "src/chatServer.rs"