all: MultiTCPServer MyTCPClient

MultiTCPServer: MultiTCPServer.c
	gcc MultiTCPServer.c -o MultiTCPServer

MyTCPClient: MyTCPClient.c
	gcc MyTCPClient.c -o MyTCPClient

clean:
	rm -f MultiTCPServer MyTCPClient
