all: EasyTCPClient.class EasyTCPServer.class EasyUDPClient.class EasyUDPServer.class

EasyTCPClient.class: EasyTCPClient.java
	javac EasyTCPClient.java

EasyTCPServer.class: EasyTCPServer.java
	javac EasyTCPServer.java

EasyUDPClient.class: EasyUDPClient.java
	javac EasyUDPClient.java

EasyUDPServer.class: EasyUDPServer.java
	javac EasyUDPServer.java

clean:
	rm -f *.class

